# generated by datamodel-codegen:
#   filename:  accept_manager.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class AcceptManagerParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
