# generated by datamodel-codegen:
#   filename:  add_members.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class AddMembersParameter(BaseModel):
    __root__: List[str]
