# generated by datamodel-codegen:
#   filename:  change_coop_share.json

from __future__ import annotations

from pydantic import BaseModel


class ChangeCoopShareParameter(BaseModel):
    __root__: str
