# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import List
from typing import Optional

from pydantic import BaseModel
from pydantic import Extra


class CoopStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    coop_share: str
    manager: str
    members: List[str]
    proposed_manager: Optional[str]
