# generated by datamodel-codegen:
#   filename:  create_coop.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel
from pydantic import Extra


class CreateCoopParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    coop_share: str
    members: List[str]
