# generated by datamodel-codegen:
#   filename:  default.json

from __future__ import annotations

from typing import Any
from typing import Dict
from typing import List
from typing import Union

from pydantic import BaseModel
from pydantic import Extra


class DefaultParameterItem(BaseModel):
    class Config:
        extra = Extra.forbid

    accept_manager: Dict[str, Any]


class DefaultParameterItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    add_fa2: str


class DefaultParameterItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    cancel_swap: str


class DefaultParameterItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    collect: str


class CreateCoop(BaseModel):
    class Config:
        extra = Extra.forbid

    coop_share: str
    members: List[str]


class DefaultParameterItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    create_coop: CreateCoop


class DefaultParameterItem5(BaseModel):
    class Config:
        extra = Extra.forbid

    remove_fa2: str


class DefaultParameterItem6(BaseModel):
    class Config:
        extra = Extra.forbid

    set_pause_collects: bool


class DefaultParameterItem7(BaseModel):
    class Config:
        extra = Extra.forbid

    set_pause_swaps: bool


class Swap(BaseModel):
    class Config:
        extra = Extra.forbid

    coop_address: str
    fa2_address: str
    objkt_id: str
    objkt_amount: str
    xtz_per_objkt: str
    royalties: str
    creator: str


class DefaultParameterItem8(BaseModel):
    class Config:
        extra = Extra.forbid

    swap: Swap


class DefaultParameterItem9(BaseModel):
    class Config:
        extra = Extra.forbid

    transfer_manager: str


class DefaultParameterItem10(BaseModel):
    class Config:
        extra = Extra.forbid

    update_fee: str


class DefaultParameterItem11(BaseModel):
    class Config:
        extra = Extra.forbid

    update_fee_recipient: str


class UpdateMetadata(BaseModel):
    class Config:
        extra = Extra.forbid

    key: str
    value: str


class DefaultParameterItem12(BaseModel):
    class Config:
        extra = Extra.forbid

    update_metadata: UpdateMetadata


class DefaultParameter(BaseModel):
    __root__: Union[
        DefaultParameterItem,
        DefaultParameterItem1,
        DefaultParameterItem2,
        DefaultParameterItem3,
        DefaultParameterItem4,
        DefaultParameterItem5,
        DefaultParameterItem6,
        DefaultParameterItem7,
        DefaultParameterItem8,
        DefaultParameterItem9,
        DefaultParameterItem10,
        DefaultParameterItem11,
        DefaultParameterItem12,
    ]
