# generated by datamodel-codegen:
#   filename:  swap.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class SwapParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    coop_address: str
    fa2_address: str
    objkt_id: str
    objkt_amount: str
    xtz_per_objkt: str
    royalties: str
    creator: str
